development:
  basedir: "/home/joshua/Projects/rsynconrails"
  datadir: "/home/joshua/Projects/rsynconrails/testdata"

test:

production:
  basedir: "/home/joshua/Projects/rsynconrails"
  datadir: "/home/joshua/Projects/rsynconrails/data"
