development:
  basedir: "/home/joshua/Projects/linuxonrails"
  datadir: "/home/joshua/Projects/linuxonrails/testdata"

test:

production:
  basedir: "/home/joshua/Projects/linuxonrails"
  datadir: "/home/joshua/Projects/linuxonrails/data"
