development:
  base_dir: "/home/joshua/Projects/rsynconrails"
  data_dir: "/home/joshua/Projects/rsynconrails/testdata"
  hosts_dir: "/home/joshua/Projects/rsynconrails/testdata/hosts"
  packages_dir: "/home/joshua/Projects/rsynconrails/testdata/packages"
  debug: false

test:

production:
  base_dir: "/home/joshua/Projects/rsynconrails"
  data_dir: "/home/joshua/Projects/rsynconrails/data"
  debug: false
